# The number of random experiment repetitions. In each run, random variants are generated and a random source variant
# is selected from which a diff is calculated. The higher the number of repeats the more random repeats for two specific
# SPL-commit pairs
experiment.repeats = 1

# The number of random variants that are generated per repeat. Only one variant is considered as source, but all variants
# are considered as target
experiment.variant.count = 5

experiment.startid = 0

# The path to the list of dataset
experiment.datasets = src/main/resources/debug.md

# The path to the main working directory of the experiment
experiment.dir.main = /home/alex/data/variability-aware-patching/simulation-files

# The path to the ground-truths
experiment.dir.ground-truths = /home/alex/data/variability-aware-patching/ground-truth

# The path to the results directory
experiment.dir.results = /home/alex/data/variability-aware-patching/results

# Whether debug files should be written
experiment.debug = true

# Maximum number of commits in a repository for a dataset to be considered for the study. If a repository has
# more commits, it is simply ignored. Values of 0 or less are automatically converted to Integer.MAX_VALUE.
experiment.dataset.max-size = 0

# Number of threads for parallel execution. Note that the bottleneck might be the IO capacity of your disk. 
experiment.thread-count = 1
