# The number of random experiment repetitions. In each run, random variants are generated and a random source variant
# is selected from which a diff is calculated. The higher the number of repeats the more random repeats for two specific
# SPL-commit pairs
# inclusive start and end
experiment.repeats.start=1
experiment.repeats.end=1
experiment.sample-file = /home/alex/data/cherry-picks/last-sample.ser
experiment.startid=0
experiment.cherry-type = Complex
# The path to the list of dataset
experiment.datasets=./src/test/resources/troublesome-cherries
# The path to the main working directory of the experiment
experiment.dir.main=/home/alex/data/cherry-picks/study-files
# The path to the results directory
experiment.dir.results=/home/alex/data/cherry-picks/results
# The path to the directory to which the SPL repos are cloned
experiment.dir.repos=/home/alex/data/cherry-picks/REPOS
experiment.processed-file=/home/alex/data/cherry-picks/results/processed.txt
# Whether debug files should be written
experiment.debug=true
# Minimum number of cherries in a repository for it to be considered for the evaluation.
experiment.dataset.min-size=-1
# Maximum number of commits in a repository for a dataset to be considered for the study. If a repository has
# more commits, it is simply ignored. Values of 0 or less are automatically converted to Integer.MAX_VALUE.
experiment.dataset.max-size=-1
# Number of threads for parallel execution. Note that the bottleneck might be the IO capacity of your disk.
experiment.thread-count=1
# Should the amount of data be reduced by sampling with a certain confidence?
experiment.enable-sampling=false
# (z) is the Z-score corresponding to your desired confidence level (for a 95% confidence level, (z = 1.96)),
sampling.z=1.10
# (e) is the margin of error (in percent, such as 5% = 0.05).
sampling.e=0.10
# (p) is the sample proportion (in percent, such as 50% = 0.5),
sampling.p=0.5
# A seed that is used during sampling to ensure repeatability of the experiments
sampling.seed=3