###
### GENERAL ###
###
# The number of EXPERIMENT_TIMEOUT_UNIT to wait for a patcher to finish patching (long)
experiment.timeout.length=5
# The time unit for the timeout, e.g., SECONDS, MINUTES, ...
experiment.timeout.unit=MINUTES
# Number of threads for parallel execution. Note that the bottleneck might be the IO capacity of your disk.
experiment.thread-count=1
# Minimum number of cherries in a repository for it to be considered for the evaluation.
# -1 means all repositories are included.
experiment.dataset.min-size=-1
# Maximum number of commits in a repository for a dataset to be considered for the study. If a repository has
# more commits, it is simply ignored. Values of 0 or less are automatically converted to Integer.MAX_VALUE.
# -1 means all repositories are included.
experiment.dataset.max-size=-1
# Which patchers should be enabled?
experiment.patcher.gnu-patch=true
experiment.patcher.git-apply=false
experiment.patcher.git-cp=true
experiment.patcher.mpatch=true

###
### PATHS ###
###
# The path to the list of dataset
experiment.datasets=evaluation-workdir/data/mined-cherries-verification
# The path to the main working directory of the experiment
experiment.dir.main=/home/alex/data/cherry-picks/study-files-verification
# The path to the results directory
experiment.dir.results=/home/alex/data/cherry-picks/results-verification
# The path to the directory to which the SPL repos are cloned
experiment.dir.repos=/home/alex/data/cherry-picks/REPOS
experiment.processed-file=/home/alex/data/cherry-picks/results-verification/processed.txt

###
### SAMPLING ###
###
experiment.sample-file = evaluation-workdir/last-sample-verification.ser
# Should the amount of data be reduced by sampling with a certain confidence?
experiment.enable-sampling=false
# (z) is the Z-score corresponding to your desired confidence level (for a 95% confidence level, (z = 1.96)),
sampling.z=1.10
# (e) is the margin of error (in percent, such as 5% = 0.05).
sampling.e=0.10
# (p) is the sample proportion (in percent, such as 50% = 0.5),
sampling.p=0.5
# A seed that is used during sampling to ensure repeatability of the experiments
sampling.seed=3
# The number of random experiment repetitions. In each run, random variants are generated and a random source variant
# is selected from which a diff is calculated. The higher the number of repeats the more random repeats for two specific
# SPL-commit pairs (inclusive start and end)
# This setting only makes sense when samping is enabled
experiment.repeats.start=1
experiment.repeats.end=1


###
### MISC ###
###
# From which run id to start the experiments. Can be used to skip experimental runs. 
experiment.startid=0
# Which type of cherry-picks should be considered (Trivial, Complex, Both)? 
experiment.cherry-type = Complex
# Whether debug files should be written. If true, the evaluation will create DEBUG directories with various files in the working directories.
experiment.debug=false
