[tool.poetry]
name = "pwm_eval"
version = "0.1.0"
description = "Result analysis scripts for patching with matching"
authors = ["anonymous"]
packages = [
    { include = "result_analysis", from = "." }
]

[tool.poetry.dependencies]
python = "<3.12"
pyyaml = "*"
matplotlib = "*"
setuptools = "*"
scipy = "*"
statsmodels = "*"
tqdm = "*"

[tool.poetry.scripts]
run-eval = "result_analysis.__main__:main"
power-simulation = "result_analysis.simulation:main"
find-example = "result_analysis.__main__:example"
find-outliers = "result_analysis.__main__:outliers"
compare-patchers = "result_analysis.__main__:compare"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
