# inclusive start and end
experiment.repeats.start=1
experiment.repeats.end=1
experiment.startid=0
# The path to the list of dataset
experiment.datasets=/home/user/simulation-files/data/cherries
# The path to the main working directory of the experiment
experiment.dir.main=/home/user/simulation-files/main/cherries
# The path to the results directory
experiment.dir.results=/home/user/simulation-files/results/cherries
# The path to the directory to which the SPL repos are cloned
experiment.dir.repos=/home/user/simulation-files/REPOS/cherries
# Whether debug files should be written
experiment.debug=false
# Minimum number of cherries in a repository for it to be considered for the evaluation.
experiment.dataset.min-size=0
# Maximum number of commits in a repository for a dataset to be considered for the study. If a repository has
# more commits, it is simply ignored. Values of 0 or less are automatically converted to Integer.MAX_VALUE.
experiment.dataset.max-size=0
# Number of threads for parallel execution. Note that the bottleneck might be the IO capacity of your disk.
experiment.thread-count=5
# Should the amount of data be reduced by sampling with a certain confidence?
experiment.enable-sampling=true
# (z) is the Z-score corresponding to your desired confidence level (for a 95% confidence level, (z = 1.96)),
# sampling.z=1.96
# Score for 99%
sampling.z=2.58
# (e) is the margin of error (in percent, such as 5% = 0.05).
# sampling.e=0.05
# smaller error
sampling.e=0.01
# (p) is the sample proportion (in percent, such as 50% = 0.5),
sampling.p=0.5
# A seed that is used during sampling to ensure repeatability of the experiments
sampling.seed=3
