writer1       = console
writer1.level = info

writer2       = file
writer2.level = info
writer2.file  = /home/user/evaluation-workdir/log.txt

writer3       = file
writer3.level = warn
writer3.file  = /home/user/evaluation-workdir/warn.txt

writer4       = file
writer4.level = debug
writer4.file  = /home/user/evaluation-workdir/debug.txt
